export const UPLOAD_IMG = "UPLOAD_IMG";
export const ADD_PRODUCT_GENERAL = "ADD_PRODUCT_GENERAL";
export const ADD_PRODUCT_GENERAL_SUCCESS = "ADD_PRODUCT_GENERAL_SUCCESS";
export const ADD_PRODUCT_DETAIL = "ADD_PRODUCT_DETAIL";
export const ADD_PRODUCT_DETAIL_SUCCESS = "ADD_PRODUCT_DETAIL_SUCCESS";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";

export const GET_PRODUCT_GENERAL = "GET_PRODUCT_GENERAL";

// export const NUMBER_CART = "NUMBER_CART";
// export const WATCH_PRODUCT_LIST = "WATCH_PRODUCT_LIST";
// export const WATCH_SINGLE_ITEM = "WATCH_SINGLE_ITEM";
// export const SEARCH_BY = "SEARCH_BY";
// export const SORT_BY = "SORT_BY";
// export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
// export const SEARCH_BY = "SEARCH_BY";
// export const SEARCH_BY = "SEARCH_BY";
