export const singleItem = {
    category: "Man",
    colors: ["White", "gray"],
    discountPrice: "350.00",
    discription: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    id: 1,
    img: "ecommerce/01.jpg",
    name: "Man's Shirt",
    note: "Simply dummy text of the printing",
    price: 100,
    review: "(250 review)",
    size: ["M", "L", "XL"],
    status: "none",
    stock: "In stock",
    tags: [("Diesel", "Hudson", "Lee")],
    variants: [
        { color: "White", images: "ecommerce/01.jpg" },
        { color: "gray", images: "ecommerce/04.jpg" },
        { color: "black", images: "ecommerce/02.jpg" },
        { color: "pink", images: "ecommerce/03.jpg" },
    ],
};
